### PR TITLE
Update of ERD docs

### PR DESCRIPTION
**Pull request by codeGobbler**
@peterntiamoah @pjsier please review. Docs have been updated to reflect change in db/seeds.rb and error handling for reports feature.

### CODE REVIEW

**Comment by codeGobbler** [comment]
Had to close due to unexpected changes in this branch.

**Comment by codeGobbler** [comment]
Ended up reverting the commit that included all the front-end changes and re-committed the ERD doc update. This PR should only update the ERD docs, but I am unsure if reverting the changes will have the same effect on the remote repo. @pjsier if you have any insight on this, I'd greatly appreciate it. Thanks guys.

**Comment by pjsier** [comment]
@codeGobbler not sure I'm following, but you can see what files were changed in the PR here https://github.com/peterntiamoah/Event-Attendance/pull/28/files. You might have to push what you reverted if it isn't here already?

**Comment by peterntiamoah** [comment]
Appreciate you taking the time to do this Alton

**Pull request merged**
